### ISSUE TITLE
Remote workspaces

### ISSUE THREAD

**Issue by garethjevans** [jenkinsci/conventional-commits-plugin#10]
### Feature Request

Handle running git commands on local and remote workspaces.

**Comment by asergeant01** [comment]
I believe i have come across this issue also. Is there a know work around?

`java.io.IOException: workspace.isRemote(), not entirely sure what to do here...`

**Comment by philippart-s** [comment]
Hi, we didn't work yet on this issue, sorry

**Comment by vehagn** [comment]
I have the same issue in my project. Any pointers on how this can be fixed?

**Comment by asergeant01** [comment]
@vehagn in the end we didn’t use the plugin, instead as we can run containers in our Jenkins we simply deployed the commitizen container and just scripted their commands

https://hub.docker.com/r/commitizen/commitizen

**Comment by philippart-s** [comment]
@asergeant01 & @vehagn release [0.11.1](https://github.com/jenkinsci/conventional-commits-plugin/releases/tag/0.11.1) should fix your problem
