### ISSUE TITLE
Add currentVersion() step

### ISSUE THREAD

**Issue by henryborchers** [jenkinsci/conventional-commits-plugin#111]
Any chance that I can use this plugin to easily determine the current version?  Something like the following would be very helpful and would allow me to remove a lot of annoying code in my pipelines.

`def CURRENT_VERSION=currentVersion()
`

**Comment by garethjevans** [comment]
Hi @henryborchers, not at the moment, but that would be a great addition.  Do you fancy submitting a PR?

**Comment by henryborchers** [comment]
I would if I knew enough Java. I've touched Java code once since 2006.

**Comment by philippart-s** [comment]
@henryborchers I can take it if you prefer and you'll test it once it's done ?

**Comment by henryborchers** [comment]
I'd be very happy to test it!!

**Comment by philippart-s** [comment]
@henryborchers the next released version will have the fix (0.10.0).
Sorry for the delay but I waited to merge another PR before merge the fix and there is fewer people who participate to this project
