### ISSUE TITLE
Write next version in a python project

### ISSUE THREAD

**Issue by philippart-s** [jenkinsci/conventional-commits-plugin#113]
### Feature Request
Updating the configuration file for a python project with the next calculated version.

**Comment by sreyan-ghosh** [comment]
Hi @philippart-s I am pretty new to opensource but want to contribute to this issue. I had a look at the closed issues related to "writing next version" in `package.json` and `pom.xml` but didn't understand what it is that is being done exactly. 

Could you guide me on what needs to be done in this issue?

**Comment by philippart-s** [comment]
Hi,

I'll glad to explain you how to contrib.
I give you more details this week-end (I'm currently at Devoxx France with less access to my computer 😉 )

**Comment by sreyan-ghosh** [comment]
Sure, no issues. I'll be waiting.

**Comment by philippart-s** [comment]
Hi again @sreyan-ghosh ,

To develop this feature you should implement the method writeVersion in the class https://github.com/jenkinsci/conventional-commits-plugin/blob/main/src/main/java/io/jenkins/plugins/conventionalcommits/utils/PythonProjectType.java.

The goal is to get the next version for a PHP project and write back in the configuration file (if it exist) to use it later (for example on a package step).

Hope it's help you 😉

**Comment by philippart-s** [comment]
PR #129  fix this issue
