### ISSUE TITLE
 Support PHP project for reading current version

### ISSUE THREAD

**Issue by philippart-s** [jenkinsci/conventional-commits-plugin#116]
### Feature Request

Read current version in a PHP project

**Comment by slim-patchy** [comment]
Hi @philippart-s Am interested in working on this issue. Can I be assigned to it?

**Comment by philippart-s** [comment]
Hi @slim-patchy ,

Of course you can work on it !
And happy new year ! :tada:

**Comment by slim-patchy** [comment]
Great, thanks @philippart-s

Happy new year to you too! 🎉

**Comment by slim-patchy** [comment]
Am doing some research about how to approach this issue, and will submit a PR once I have the code ready

**Comment by slim-patchy** [comment]
@philippart-s Looks like the best bet/option is to use either `git` tags or to use the `composer.json` configuration file if a version number is indeed supplied. But the more modern way appears to be `git` tags based, not the ideal solution in our given context. What do you think?

**Comment by slim-patchy** [comment]
I am kind of leaning towards using the `composer.json` config file as a means to check for package version, but it does not appear to be the best or even encouraged practice according to the [official documentation](https://getcomposer.org/doc/04-schema.md#version). Hence, the most viable way would be to use git tags, with something like the following:
```shell
git describe --tags --abbrev=0
```
For PHP I think in a way this makes some sense as PHP can be used in a variety of ways, so there tends not to be an established way to read off the current version number using PHP package managers like Composer. Meanwhile, let me also check out the major PHP support frameworks like Laravel to see how versioning can be done, like as done here: https://github.com/antonioribeiro/version

**Comment by philippart-s** [comment]
> @philippart-s Looks like the best bet/option is to use either `git` tags or to use the `composer.json` configuration file if a version number is indeed supplied. But the more modern way appears to be `git` tags based, not the ideal solution in our given context. What do you think?

Hi @slim-patchy ,
If it's hard to determine the current version for PHP project using information in a file the use of git tag is the default behavior of the plugin.

We have a method for that : https://github.com/jenkinsci/conventional-commits-plugin/blob/46b9398908286f660f43bc895d6110ce5cafc20b/src/main/java/io/jenkins/plugins/conventionalcommits/utils/CurrentVersion.java#L19
And the latest tag is always get with : https://github.com/jenkinsci/conventional-commits-plugin/blob/46b9398908286f660f43bc895d6110ce5cafc20b/src/main/java/io/jenkins/plugins/conventionalcommits/CurrentVersionStep.java#L73 that use an helper to get tags in git history : https://github.com/jenkinsci/conventional-commits-plugin/blob/46b9398908286f660f43bc895d6110ce5cafc20b/src/main/java/io/jenkins/plugins/conventionalcommits/utils/TagsHelper.java#L23

In fact the plugin always check the last tag in git history to find current version.

So if you don't create a PHPProjectType class to compute next version and write down in a file a PHP project will use the default behavior: get the last git tag in the history.

I thought composer was a common solution in the PHP world but I'm not a PHP developer :wink: 

Hope I answer of your question

**Comment by slim-patchy** [comment]
Hi @philippart-s Yeah, it's actually a bit disappointing to realise that the best practice as advocated by the org behind Composer is not to include any versioning info in their config file `composer.json`, even though this is an option for versioning if the PHP developer does choose to do so. Let me see what I could put together to computer the next version for PHP instead... Will need to check the details first.

**Comment by slim-patchy** [comment]
Should we close this issue then for me to move on to #117?

**Comment by philippart-s** [comment]
> Should we close this issue then for me to move on to #117?

I'm not sure that the #117 can be done if it is not possible to have a file where read / store the version.
I think the #117 and this PR are linked : either we code them or we close them, what do you think ?

**Comment by slim-patchy** [comment]
Yeah, I think you are right. How about checking if the version is indeed not included in the `composer.json` file before falling back onto the default `git tag` routine? I think I will be able to come up with a PR for that.

**Comment by philippart-s** [comment]
> How about checking if the version is indeed not included in the `composer.json` file before falling back onto the default `git tag` routine? I think I will be able to come up with a PR for that.

It will be perfect to me, but it's more development to do 😉 .
If you are interested to develop this use case don't hesitate !

**Comment by slim-patchy** [comment]
Glad you liked the idea! Sure, let me do a bit research before preparing for a follow-up PR.

**Comment by slim-patchy** [comment]
Sorry for the long delay @philippart-s! Will be submitting a PR within the next week or two.

**Comment by philippart-s** [comment]
> Sorry for the long delay @philippart-s! Will be submitting a PR within the next week or two.

No problem, it's an open source project.
The aim is to take pleasure to code it, no pressure 😉 

Personally I just started a new job so my schedule is quite busy, I have to code a feature since 2 months!
