### ISSUE TITLE
Support Go project for reading current version

### ISSUE THREAD

**Issue by philippart-s** [jenkinsci/conventional-commits-plugin#118]
### Feature Request

Read current version in a Go project

**Comment by sshiv5768** [comment]
Hey, @philippart-s
I would love to work on this issue can you give some brief info about this issue.

**Comment by philippart-s** [comment]
hi @sshiv5768 ok !

**Comment by philippart-s** [comment]
@sshiv5768 did you still interested to work on this issue ?

**Comment by slim-patchy** [comment]
Hi @philippart-s I see no one is currently assigned to the project and would like to start work on it. Can I be assigned to the issue?

**Comment by philippart-s** [comment]
Hi, @slim-patchy.

Yes you can, I assign the issue to you.

Thanks 😉

**Comment by slim-patchy** [comment]
Thanks @philippart-s I will follow up with a PR soon

**Comment by slim-patchy** [comment]
I am currently working out how best to put some code to parse the very long output of the command `go list -m -versions`, is the directory `src/main/java/io/jenkins/plugins/conventionalcommits/utils` a good place for it? For a background the output for the [`hey`](https://github.com/rakyll/hey) repo can look something like the following:
```shell
go list -m: loading module retractions for github.com/rakyll/hey@v0.1.0: verifying go.mod: github.com/rakyll/hey@v0.1.4/go.mod: initializing sumdb.Client: open /opt/homebrew/bin/go/pkg/sumdb/sum.golang.org/latest: not a directory
```
So some regex may be warranted for such a task...

**Comment by philippart-s** [comment]
yes if your code is GO oriented (or just used for a Go project) put it in a class `GoProjectType`

**Comment by slim-patchy** [comment]
Sure, no problem! Have just completed a first draft of the code for Go support, on to the testing stage next. Should be done over the next few days.

**Comment by slim-patchy** [comment]
Just submitted PR #156 to follow-up on this issue.

**Comment by philippart-s** [comment]
I'll review it as soon as possible
