### ISSUE TITLE
Use contain in place of startWith in the search of attributes version

### ISSUE THREAD

**Issue by philippart-s** [jenkinsci/conventional-commits-plugin#142]
### Dependencies

see https://github.com/jenkinsci/conventional-commits-plugin/pull/129#discussion_r739318545

### Feature Request

Several piece of code use `startsWith` to find the version attribute in the configuration file.
For file with indentation it's combining with `contain` to ignore spaces or tabulations.

Uses `contain` will be sufficient or trim spaces and tabulation before the search.

Example of such code:
```java
if (!isVersionTag && Arrays.stream(matchingWords)
                  .anyMatch(isIndented ? line.toLowerCase()::contains :
                          line.toLowerCase()::startsWith))
```

**Comment by ReyhanPatria** [comment]
Hi! I would like to work on this, this seems simple enough for my first issue. I would like to be assigned to this. Thanks!

**Comment by philippart-s** [comment]
Welcom @ReyhanPatria , thanks !
