### ISSUE TITLE
Improve contributing documentation to add install details

### ISSUE THREAD

**Issue by slim-patchy** [jenkinsci/conventional-commits-plugin#152]
## Summary

Currently it is hard for a newcomer to start contributing because of some missing details (like how to run), that currently can only be accessed via the generic Jenkins contributing documentation at https://github.com/jenkinsci/.github/blob/master/CONTRIBUTING.md. Would like to prepare a doc PR to fix this issue to add to https://github.com/jenkinsci/conventional-commits-plugin/blob/main/.github/CONTRIBUTING.md for easy reference. Please assign me this issue if possible. 

## Reference

* https://github.com/jenkinsci/conventional-commits-plugin/blob/main/.github/CONTRIBUTING.md

**Comment by philippart-s** [comment]
hello @slim-patchy.

I agree with you, I assign to you this issue :wink:

**Comment by slim-patchy** [comment]
Thanks @philippart-s!

**Comment by slim-patchy** [comment]
Am thinking about adding details in the [CONTRIBUTING.md](https://github.com/jenkinsci/conventional-commits-plugin/blob/main/.github/CONTRIBUTING.md) file with at least the following:

1. A friendly reminder to first install Jenkins before trying to install this plugin.
2. A suggestion to use the `mvn hpi:run` command to build and run the plugin.
3. A pointer to state that using the default config, Jenkins would be launched on http://localhost:8080/jenkins/. 

I will go through the documentation at [the official plugin tutorial](https://www.jenkins.io/doc/developer/tutorial/) and do some experimentation on my own to see if some tips, hints, caveats are warranted, before preparing and submitting a PR to follow up.

**Comment by philippart-s** [comment]
Hi,


I agree with you.
You can also set links to the generic documentation to avoid duplicate content and do maintenance when it change in the generic documentation.

**Comment by slim-patchy** [comment]
Hi @philippart-s, sure I can do that. Also for the testing part I think I better include some reminder for contributors to add tests for their PRs where appropriate, if the code contributed will affect the output in any way, shape, or form. Just realised I almost forgot that all-important step in the CI/CD process.

**Comment by philippart-s** [comment]
for me whatever the contribution, tests must be exist :wink:
