### ISSUE TITLE
java.io.IOException: workspace.isRemote(), not entirely sure what to do here...

### ISSUE THREAD

**Issue by venkatvaranasi8421** [jenkinsci/conventional-commits-plugin#173]
We are trying to use this plugin for our project to use semantic versioning for release. But when we check in code and try to build using jenkins file we are getting this error:

java.io.IOException: workspace.isRemote(), not entirely sure what to do here...
	at io.jenkins.plugins.conventionalcommits.CurrentVersionStep$Execution.run(CurrentVersionStep.java:70)
	at io.jenkins.plugins.conventionalcommits.CurrentVersionStep$Execution.run(CurrentVersionStep.java:42)
	at org.jenkinsci.plugins.workflow.steps.SynchronousStepExecution.start(SynchronousStepExecution.java:38)

What is this issue and what should we do to resolve this

**Comment by philippart-s** [comment]
Hi,

It appears that you use a remote workspace (if not there is a bug in the plugin 😉).
The remote workspace is not yet supported by the plugin.

We don't do tests so I can't tell you if it is possible to use the plugin is this context.

Can you detail what kind of remote workspace do you use and the use case ?

**Comment by traghu84** [comment]
Hi,

I am also facing the same issue, where as in our case we are spinning of Docker container for Jenkins Agents to build the job which will be destroyed immediately once build completes.

So if i understand correctly this plugin does support only when the build happens on the master?

**Comment by philippart-s** [comment]
I don't know, I came after the creation of the plugin and became maintainer because lot of people left the plugin development.

I try to keep it alive but I haven't the all history.

**Comment by Rossbro2** [comment]
Same issue here @philippart-s.  I am running a multibranch pipeline job on a Jenkins node that is not the master.

As @moritzrupp mentioned - what is the requirement for running on the master?

Also, is this expected to be fixed anytime soon?  Thank you.

**Comment by Rossbro2** [comment]
Looks like [this code](https://github.com/jenkinsci/conventional-commits-plugin/blob/afd65531d09d323716aa1faf296969af52a535d0/src/main/java/io/jenkins/plugins/conventionalcommits/NextVersionStep.java#L232) was introduced from PR #9, if that helps with troubleshooting at all...

**Comment by philippart-s** [comment]
> As @moritzrupp mentioned - what is the requirement for running on the master?

As I explain I came after the creation of the plugin, I think there is no reason just the plugin was not tested on agent.

> Also, is this expected to be fixed anytime soon? Thank you.

Expected to be fixed yes but the question is when.
Almost all developers left this project and I'm quite alone.

I try to have a look during the next days and give you a feedback on the correction

**Comment by philippart-s** [comment]
@moritzrupp I made a quick fix (remove the if 😅) and tested with a local main instance and a local remote agent.

All seem good but it's not a real production test because I have only one machine.

When the new version will be release I ping you to test the new version and tell me if it fixes the issue.

**Comment by Rossbro2** [comment]
> When the new version will be release I ping you to test the new version and tell me if it fixes the issue.

Sounds great - thank you @philippart-s!

**Comment by philippart-s** [comment]
@Rossbro2 & @moritzrupp release [0.11.1](https://github.com/jenkinsci/conventional-commits-plugin/releases/tag/0.11.1) should fix your problem
