### ISSUE TITLE
Support reading the current version from a package.json

### ISSUE THREAD

**Issue by garethjevans** [jenkinsci/conventional-commits-plugin#18]
### Feature Request

Support reading / writing the version from a package.json

**Comment by philippart-s** [comment]
Hi @garethjevans ,

Can I try to work on this issue ?
I'am a new to contributing to Jenkins / Jenkins plugins, is it ok for you ?

Is there any code convention to follow (I have read the default contributing) ?

Regards.

**Comment by philippart-s** [comment]
@ADI10HERO is it mean that it's ok for me to work on this issue ?

**Comment by ADI10HERO** [comment]
> @ADI10HERO is it mean that it's ok for me to work on this issue ?

Hey @philippart-s, yes please, by all means :) 

Would you like to:
1. Get this issue assigned to yourself
2. Join the [gitter channel](https://gitter.im/jenkinsci/conventional-commits-plugin) for this project to chat/discuss your approach

**Comment by philippart-s** [comment]
@ADI10HERO can't assign to my self, I think you have the rigth to do the assignment
