### ISSUE TITLE
nextversion does not work

### ISSUE THREAD

**Issue by itrice** [jenkinsci/conventional-commits-plugin#205]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Can not calculate the version, from the commit messages. Only BREAKIN CHANGE patten works. The others are not working.
e.g 
![image](https://user-images.githubusercontent.com/10216853/177461763-84ebade4-eabb-4c2d-894a-3822aa1e5d96.png)
From the above picture, the version should be 2.1.0, but the actual result is 2.0.0.

### Reproduction steps

1. git push commit message  "BREAKING CHANGE: BC"
2. git push commit message  "feat: add a new feature"
3. git push commit message "fix: minor bug fix"

### Expected Results

the version should be 2.1.1

### Actual Results

version is  2.0.0

**Comment by garethjevans** [comment]
Hi @itrice, looking at the commits you have created since the previous release, I would expect the next version to be `2.0.0` and not `2.1.1`.
