### ISSUE TITLE
Support multiline commit messages

### ISSUE THREAD

**Issue by garethjevans** [jenkinsci/conventional-commits-plugin#22]
### Feature Request

the current implementation only reads the first line from the commit message, this may miss some conventional commit messages. According to the spec, the following is a valid commit message:

```
feat: allow provided config object to extend other configs

BREAKING CHANGE: `extends` key in config file is now used for extending other config files
```

currently this will be treated as a minor release, but should be treated as a major release.

**Comment by jonyto123** [comment]
Also can you add !: spec to breaking change? when 'appends a ! after the type/scope'.
