### ISSUE TITLE
Support reading the current version from a python setup.cfg

### ISSUE THREAD

**Issue by henryborchers** [jenkinsci/conventional-commits-plugin#48]
### Feature Request

Support reading / writing the version from a setup.cfg from a python project

An example of this file could look like...

```
[metadata]
name = mypackage
version = 0.1.23
url = http://www.example.com/mypackage
author = Fake author
author_email = fake@example.com
description = My Package does something very interesting
long_description = file: ABOUT.rst
license = University of Illinois/NCSA Open Source License
license_file = LICENSE
classifiers =
    Programming Language :: Python :: 3.7
    License :: OSI Approved :: University of Illinois/NCSA Open Source License
    Topic :: System :: Archiving :: Packaging
```

**Comment by ADI10HERO** [comment]
Hello, @henryborchers
I had a couple of questions:
1. In the python project, a `setup.py` file also (almost) always exists, right?

**Comment by henryborchers** [comment]
Short answer: 
The setup.py almost always exists for Python projects. At least the time being... 

Longer answer: 
However, that is changing very rapidly. In Python the acceptance of the Python proposal, [PEP-517](https://www.python.org/dev/peps/pep-0517/) is making setup.py no longer a necessary for creating Python distribution packages. Python developers are moving away from using setup.py if they don't need it or using new build systems that doesn't require a setup.py. 

The Python community has finally accepted a standard place to put [unified project metadata](https://www.python.org/dev/peps/pep-0621/) in a declarative and parsable format usable across build systems, [pyproject.toml](https://www.python.org/dev/peps/pep-0518/). Unfortunately, it's so new, that nothing has implemented it yet.  Before the acceptance of this, storing static package metadata for Python projects in a setup.cfg has been the closest thing to a standard. I don't see it going away anytime soon.

**Comment by ADI10HERO** [comment]
Gotcha! Thank you so much for your answer (especially the longer one). 

The reason I was asking for `setup.py` was, it's easy to get the current version using the command: `python setup.py --version`

It covers the case when the version is mentioned under metadata in `setup.cfg` and even when it's dynamic (`version = get_version()`) i.e. using some other function or variable to set the version and not directly written (`version = 1.1.1` ) in either of the setup files.

I will be reading on unified project metadata and `pyproject.toml` next. I researched on getting (please read as "evaluating and printing") the current version from `setup.cfg`, so in `setup.cfg`, everything is static so...
1.  I can write cases when the version is directly written as `version = major.minor.patch` and when it's attributing to another file, eg. `version= file: path/to/version.txt`
2. Research more on how to evaluate the current version from `setup.cfg`, something similar to `python setup.py --version`

If you have any thoughts/insights on 2 would like to discuss

**Comment by henryborchers** [comment]
I'm happy to provide any help with this that I can.

One thought off the top of my head about not using "setup.py --version". I used to use this to solve this problem myself but I would run into an issue if the setup.py includes any print statements. 

My current strategy for getting this to work consistently is something like this...
```
script{
     sh 'python setup.py dist_info'
     def metadataFile = findFiles( glob: '*.dist-info/METADATA')[0]
     def metadata = readProperties(interpolate: true, file: metadataFile.path )
     def Version = metadata.Version
}
```
