### ISSUE TITLE
Support reading the current version from a maven pom.xml

### ISSUE THREAD

**Issue by garethjevans** [jenkinsci/conventional-commits-plugin#5]
### Feature Request

Support reading the version from a maven pom.xml.  Could either simply parse the the xml or use the `help:evaluate` command to evaluate the version of `project.version` (may be a better approach for more complex projects)

**Comment by fowlie** [comment]
+1 for this one :+1: 

I hope you will use the `help:evaluate` approach. Otherwise, it can be difficult for Maven multi module projects.
