### ISSUE TITLE
Add documentation / configuration files to configure IDE

### ISSUE THREAD

**Issue by philippart-s** [jenkinsci/conventional-commits-plugin#51]
### Feature Request
To avoid unreadable PR it'll be nice to share (by documentation ou config file like .editorconfig) the IDE configuration.
The code format option  in the IDE will not make a mess in the PR 😉

**Comment by garethjevans** [comment]
Rather than adding the project files, it may be worth adding configuring a checkstyle formatter in the pom.xml so that it should work across all IDEs? what do you think? I can push a PR as an example.

**Comment by philippart-s** [comment]
Yes it's a good idea, but if I understand how it works this is to generate reporte not format automatically the code, the .editorconfig file is recongnize by Idea, VsCode ans Eclipse and can be used to set the minimum configuration like space in place of tab, max line length,end line style, ... And the IDE format the code based on this file.
I thing a combination of checkstyle and editorconfig may be a good solution 😉 (mor eexplanation for editorconfig  : https://editorconfig.org/)

**Comment by philippart-s** [comment]
@garethjevans & @ADI10HERO if it's ok for you, you can assign me the issue.
As mentionned in the gitter we'll can saw by the example what is the best solution 😉 .
Ok for you ?

**Comment by philippart-s** [comment]
@garethjevans & @ADI10HERO, I think my idea is not so good seeing what the checkstyle plugin's do.
I think with the plugins in each of IDE we can do the same result by importing the checkstyle rule used by the maven plugin (Google java's checkstyle if I undertand the documentation).

@garethjevans I think your idea is better we can use the default configuration or create a custom configuration for the project as you want

Do we add the checkstyle verification iin the lifecycle of the maven project ?
In this case do you want I try to update the pom with this kind of verification and propose a custom checkstyle configuration (if needed) ?

**Comment by ADI10HERO** [comment]
> Do we add the checkstyle verification iin the lifecycle of the maven project ?
> In this case do you want I try to update the pom with this kind of verification and propose a custom checkstyle configuration (if needed) ?

Hey @philippart-s , @garethjevans's PR (#55) adds a check (though using GitHub actions), is it something similar to what you're suggesting?

**Comment by philippart-s** [comment]
yes you're right I've missed this PR (sorry).
The job is done as he updated the pom with the chekstyle configuration :wink: 

It's totally what I imagined ! For me this PR fixe this issue :wink: 

Furthemor the job you done in the #72 corroborate that is the good approch to use checkstyle maven plugin and the checkstyle plugin int the IDEs.

**Comment by ADI10HERO** [comment]
Then I guess adding a `fixes #51` in the PR would do the Job? 😄

**Comment by ADI10HERO** [comment]
@garethjevans, @philippart-s  can we close this?

**Comment by philippart-s** [comment]
ok for me
