### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by ADI10HERO** [jenkinsci/conventional-commits-plugin#70]
### Feature Request

A go-to file for the users to contribute/add more project types to the project

**Comment by abxhr** [comment]
I would love to work on this! 🙋‍♂️
Are there any specific instructions that should be mentioned in the `CONTRIBUTING.md` file?

**Comment by philippart-s** [comment]
Hi,
In my opinion a link to the developer guidelines (https://www.jenkins.io/doc/developer/tutorial/prepare/).
I'd like this kind of information : https://github.com/jenkinsci/ansicolor-plugin/blob/master/.github/CONTRIBUTING.md
Remind that tests must be provided (the PR template do this but I think it's not bad to remind again :wink: ).

An explanation on how named the PR regarding the action _labeler_ (https://github.com/jenkinsci/conventional-commits-plugin/blob/main/.github/labeler.yml) : it avoid for maintainer to rename PR.

The project use chekstyle (Google checkstyle : https://checkstyle.sourceforge.io/google_style.html), it's may be useful to configure IDE.
Obvious but all the checks in the PR must be success.

And all ideas that help to onboard a new developer !

Perhaps  @ADI10HERO or @garethjevans have other ideas ?
