### ISSUE TITLE
If tag is not created with annotated option it is not used to get the next version

### ISSUE THREAD

**Issue by philippart-s** [jenkinsci/conventional-commits-plugin#76]
### Version report

Jenkins and plugins versions report:

```
Nightly version of the plugin (main branch).
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Linux.
```

### Reproduction steps

- Create an annotated tag : `git tag -a 0.1.0`
- Create a non annotated tag : `git tag 0.2.0`
- Execute  the line in the code that get the last tag :  https://github.com/jenkinsci/conventional-commits-plugin/blob/e9ec5b420984ae811a7372c9f416c98ab9276662/src/main/java/io/jenkins/plugins/conventionalcommits/NextVersionStep.java#L132

### Results

Expected result:

The `lastestTag` value must be 0.2.0

Actual result:

The `latestTag` field value is 0.1.0

**Comment by ADI10HERO** [comment]
@garethjevans, @philippart-s 
Tested this on a sample maven and python project and I was able to replicate the issue but this only happens when (multiple) tags are applied to the same commit.

To see all tags applied to the same commit: `git log --oneline --decorate=short`

When multiple commits are tagged, the command `git describe --tags` gets the latest tag (irrespective of it being annotated or not)

**Comment by philippart-s** [comment]
@ADI10HERO effectively, I think it's not a good thing to create two tags in the same commit but it can append ...
We can choose to not support these kind of git usage or try to get all tags created.

If we choose to list all tags regardless of their creation there is also the command `git tag -l` which list all the tags created (annotate or not, in the same commit or not).

If you want I can try to propose a PR to test this approach ?

**Comment by bpedersen2** [comment]
I recommend to only use annotated tags by default. 
Reasons: 
 - on-annotated tags are often used for local-only tagging and you would not want those to mess with your versioning.
   They do not contain infos about who and when the tagging happend.
   It has reason that  git describe will only look at annotated tags
 -  some git-backends (e.g. gerrit ) won't allow to push non-annotated tags at all
 - 
Allowing non-annotated tags could be enabled by an option (same as git describe --always).

**Comment by philippart-s** [comment]
Totally agree with you for the good practice of use annotated commit 😉.
The only point is that the user must know that if he do a non annotated commit the version will be no bumped.

As you say we can add a parameter that allow to use non annotated commit in the compute of the next version or at least we write it explicitly in the documentation that non annotated commit are not supported.

**Comment by philippart-s** [comment]
If it's ok for everybody I take this issue :wink:
